"""Add list description

Revision ID: 686ddf50967d
Revises: 899a2575d09a
Create Date: 2022-06-08 21:08:18.459205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686ddf50967d'
down_revision = '899a2575d09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'description')
    # ### end Alembic commands ###
