"""Rename url_string url_slug

Revision ID: 7decf9e2115c
Revises: 686ddf50967d
Create Date: 2022-06-10 11:42:19.478394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7decf9e2115c'
down_revision = '686ddf50967d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('url_slug', sa.String(), nullable=False))
    op.drop_constraint('polls_url_string_key', 'polls', type_='unique')
    op.create_unique_constraint(None, 'polls', ['url_slug'])
    op.drop_column('polls', 'url_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('url_string', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'polls', type_='unique')
    op.create_unique_constraint('polls_url_string_key', 'polls', ['url_string'])
    op.drop_column('polls', 'url_slug')
    # ### end Alembic commands ###
