"""Initial migration.

Revision ID: 899a2575d09a
Revises: 
Create Date: 2022-06-08 19:08:55.795124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '899a2575d09a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('url_string', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'polls', ['url_string'])
    op.drop_column('polls', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'polls', type_='unique')
    op.drop_column('polls', 'url_string')
    # ### end Alembic commands ###
